bid/urls.py
""" urls for the bid module """
from django.urls import path
from .views import BidListView, BidCreateView, BidDetailView, BidDeleteView


urlpatterns = [
    path('', BidListView.as_view(), name='bid_list'),
    # path('partner/<int:partner_pk>/', BidListView.as_view(), name='bid_list'),
    #path('partner/<int:partner_pk>/new/', BidCreateView.as_view(), name='bid_create'),
    path('for/deal/<int:deal_pk>/new/', BidCreateView.as_view(), name='bid_create'),
    path('<int:pk>/', BidDetailView.as_view(), name='bid_detail'),
    path('<int:pk>/update/', BidDetailView.as_view(), name='bid_update'),
    path('<int:bid_pk>/delete/', BidDeleteView.as_view(), name='bid_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from config import settings


urlpatterns = [
    path('', include('core.urls')),
    path('bid/', include('bid.urls')),
    path('user/', include('user.urls')),
    path('category/', include('category.urls')),
    path('listing/', include('listing.urls')),
    path('search/', include('search.urls')),
    path('chat/', include('chat.urls')),
    path('deal/', include('deal.urls')),
    path('market/', include('market.urls')),
    path('feedback/', include('feedback.urls')),
    path('location/', include('location.urls')),
    path('calculator/', include('calculator.urls')),

    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('pwa.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

location/urls.py
""" urls for location module """
from django.urls import path
from .views import LocationCreateView, LocationDeleteView, LocationDetailView,\
    LocationListView, LocationUpdateView


urlpatterns = [
    path('', LocationListView.as_view(), name='location_list'),
    path('new/', LocationCreateView.as_view(), name='location_create'),
    path('<int:pk>/', LocationDetailView.as_view(), name='location_detail'),
    path('<int:pk>/update', LocationUpdateView.as_view(), name='location_update'),
    path('<int:pk>/delete', LocationDeleteView.as_view(), name='location_delete'),
]

location/models.py
""" models for the location module """
from django.utils.translation import gettext_lazy as _
from django.db import models
from config.settings import AUTH_USER_MODEL, LOGGER
from action.models import create_action


class Location(models.Model):
    """ a location can be a location of push, pull or market (later deal) """
    title = models.CharField(
        max_length=20,
        verbose_name=_('title'),
        )
    user = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_('user'),
        )
    lon = models.DecimalField(
        default=0.0,
        max_digits=10,
        decimal_places=7,
        verbose_name=_('longitude'),
        )
    lat = models.DecimalField(
        default=0.0,
        max_digits=10,
        decimal_places=7,
        verbose_name=_('latitude'),
        )
    description = models.TextField(
        blank=True,
        verbose_name=_('description'),
        )
    chat = None

    @property
    def deals(self):
        """ Deals of this location
        :returns: QuerySet(Deal)
        """
        return self.deal_set.all()

    @property
    def markets(self):
        """ markets of this location
        :returns: QuerySet(Market)
        """
        return self.market_set.all()

    @property
    def pushs(self):
        """ pushs of this location
        :returns: QuerySet(Push)
        """
        return self.push_set.all()

    @property
    def pulls(self):
        """ pulls of this location
        :returns: QuerySet(Pull)
        """
        return self.pull_set.all()

    def save(self, *args, **kwargs):  # pylint: disable=signature-differs
        log_string = 'Location {}: title={} user={} lon={} lat={}'.format(
            'updated' if self.pk else 'created',
            str(self.title),
            str(self.user),
            str(self.lon),
            str(self.lat),
            )
        LOGGER.info(log_string)
        if not create_action(self.user, 'FIRST_LOCATION_CREATED'):
            create_action(self.user, 'LOCATION_CREATED')
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('location')
        verbose_name_plural = _('locations')

location/views.py
""" views of the location module """
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.urls.base import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Location


# pylint: disable=too-many-ancestors
class LocationListView(LoginRequiredMixin, ListView):
    """ ListView of locations """
    model = Location
    context_object_name = 'locations'

    def get_queryset(self):
        return self.request.user.locations


class LocationDetailView(LoginRequiredMixin, DetailView):
    """ DetailView of a single location """
    model = Location
    context_object_name = 'location'


class LocationCreateView(LoginRequiredMixin, CreateView):
    """ CreateView for a new location """
    model = Location
    fields = ['title', 'lat', 'lon', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return UpdateView.form_valid(self, form)

    def get_success_url(self):
        return self.request.GET.get('next', reverse('home'))


class LocationUpdateView(LoginRequiredMixin, UpdateView):
    """ UpdateView for a existing location """
    model = Location
    fields = ['title', 'lon', 'lat', 'description']

    def get_success_url(self):
        return self.request.GET.get('next', reverse('home'))


class LocationDeleteView(LoginRequiredMixin, DeleteView):
    """ DeleteView for a location """
    model = Location
    template_name = 'location/location_delete.html'

    def get_success_url(self):
        return self.request.GET.get('next', reverse('home'))

location/templates/location/location_delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block help %}
  {% include 'market/inc/help.html' %}
{% endblock %}


{% block content %}
<form method="post">{% csrf_token %}
    <p>{% trans 'market' %} "{{ object }}" {% trans 'delete' %}?</p>
    <input type="submit" value="Bestätigen">
</form>
{% endblock %}

location/templates/location/location_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load i18n %}

{% block help %}
  {% include 'location/inc/help.html' %}
{% endblock %}


{% block head %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>

<script>
  $(document).ready(function() {
    var mymap = L.map('mapid').setView(["{{ location.lat|stringformat:'f' }}", "{{ location.lon|stringformat:'f' }}"], 10);

    L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
      maxZoom: 18,
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
        '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
        'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
      id: 'mapbox/streets-v11',
      tileSize: 512,
      zoomOffset: -1
    }).addTo(mymap);
    var marker = L.marker(["{{ location.lat|stringformat:'f' }}", "{{ location.lon|stringformat:'f' }}"]).addTo(mymap);
  });
</script>
{% endblock %}


{% block content %}
<div class="container-fluid border">
  <div class="row">
    <div class="col-12 p-0">
      <div id="mapid" style="height:400px;z-index:0;"></div>
    </div>
  </div>
</div>

<hr class="my-5">

<div class="container-fluid border">
  <div class="row">
    <div class="col-12">
      <b>{% trans 'description'|title %}:</b>
    </div>
    <div class="col-12">
    {{ location.description }}
    </div>
  </div>
</div>
{% endblock %}

location/templates/location/location_form.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block help %}
  {% include 'location/inc/help.html' %}
{% endblock %}


{% block head %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin=""></script>

<script>
  $(document).ready(function() {
    var mymap = L.map('mapid').setView([49.149266, 9.198006], 10);

    L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
    	maxZoom: 18,
    	attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
    		'<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
    		'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    	id: 'mapbox/streets-v11',
    	tileSize: 512,
    	zoomOffset: -1
    }).addTo(mymap);
    var marker = L.marker([$('#id_lon').val(), $('#id_lat').val()], {draggable:'true', autoPan:'true'}).addTo(mymap);
    
    marker.on('drag', function(ev){
    	lat = ev.latlng.lat;
    	lon = ev.latlng.lng;
    	$('#id_lat').val(lat.toFixed(7));
    	$('#id_lon').val(lon.toFixed(7));
    });

    mymap.addEventListener('click', function(ev){
    	lat = ev.latlng.lat;
    	lon = ev.latlng.lng;
    	$('#id_lat').val(lat.toFixed(7));
    	$('#id_lon').val(lon.toFixed(7));
    	marker.setLatLng([$('#id_lat').val(), $('#id_lon').val()]);
    });
  });
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.css">
<script>
  $(document).ready(function() {
  	$('.chosen-select').chosen();
  });
</script>
<style>
  #id_users_chosen{width:100%!important;}
</style>
{% endblock %}

{% block content %}

<div class="row">
  <div class="col px-0">
    <div class="alert alert-info" role="alert">
      Wähle deinen Ort auf der Karte
    </div>
  </div>
</div>
<div class="row">
   <div id="mapid" class="col" style="height:400px;z-index:0;"></div>
  </div>
  <div class="row">
    <div class="col p-0">
	<form method="post" enctype="multipart/form-data">
		{% if form.errors %}
		<div class="alert alert-danger" role="alert">
			{{ form.errors }}
			</div>
		{% else %}
		{% endif %}
		{% csrf_token %}
		<table class="table table-striped table-bordered table-hover">
			{{ form.as_table }}
		</table>
		<button class="btn btn-primary btn-block" type="submit">{% trans 'save'|title %}</button>
	</form>
    </div>
</div>
{% endblock %}

location/templates/location/location_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block help %}
  {% include 'location/inc/help.html' %}
{% endblock %}


{% block content %}
  {% include 'location/solo/location_list.html' %}
{% endblock %}