bid/urls.py
""" urls for the bid module """
from django.urls import path
from .views import BidListView, BidCreateView, BidDetailView, BidDeleteView


urlpatterns = [
    path('', BidListView.as_view(), name='bid_list'),
    # path('partner/<int:partner_pk>/', BidListView.as_view(), name='bid_list'),
    #path('partner/<int:partner_pk>/new/', BidCreateView.as_view(), name='bid_create'),
    path('for/deal/<int:deal_pk>/new/', BidCreateView.as_view(), name='bid_create'),
    path('<int:pk>/', BidDetailView.as_view(), name='bid_detail'),
    path('<int:pk>/update/', BidDetailView.as_view(), name='bid_update'),
    path('<int:bid_pk>/delete/', BidDeleteView.as_view(), name='bid_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from config import settings


urlpatterns = [
    path('', include('core.urls')),
    path('bid/', include('bid.urls')),
    path('user/', include('user.urls')),
    path('category/', include('category.urls')),
    path('listing/', include('listing.urls')),
    path('search/', include('search.urls')),
    path('chat/', include('chat.urls')),
    path('deal/', include('deal.urls')),
    path('market/', include('market.urls')),
    path('feedback/', include('feedback.urls')),
    path('location/', include('location.urls')),
    path('calculator/', include('calculator.urls')),

    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('pwa.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
""" urls for core module - these are the root urls """
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from core.sitemaps import SITEMAPS
from .views import AboutView, DashboardHomeView, DonateView, TermsView, ImpressumView


urlpatterns = [
    path('', DashboardHomeView.as_view(), name='home'),
    path('', DashboardHomeView.as_view(), name='dashboard_home'),
    path('about/', AboutView.as_view(), name='about'),
    path('terms-and-conditions/', TermsView.as_view(), name='terms'),
    path('impressum/', ImpressumView.as_view(), name='impressum'),
    path('donate/', DonateView.as_view(), name='donate'),
    path('spende/', AboutView.as_view()),

    path('sitemap.xml', sitemap, {'sitemaps': SITEMAPS}, name='sitemap')
]

chat/models.py
""" models for chat module """
from django.utils.translation import gettext_lazy as _
from django.dispatch.dispatcher import receiver
from django.db.models.signals import post_save
from django.db import models
from config.settings import AUTH_USER_MODEL, LOGGER
from action.models import create_action


class ChatType(models.IntegerChoices):
    """ Type of the Chat
    DEFAULT - No chat should become that
    USER - Chat with user constellation as selector
    MARKET - Chat that is created by market (dynamic user constellation)
    LOBBY - One single chat that is used by all (no/dynamic user constellation)
    """
    DEFAULT = 0, _('default')
    USER = 10, _('user')
    MARKET = 20, _('market')
    LOBBY = 100, _('lobby')

    @classmethod
    def by_number(cls, number):
        """ select chat type by number
        :param number: integer of the chat type to select
        :returns: ChatType.X
        """
        return cls(number)


class ChatMessage(models.Model):
    """
    creates list of all users that should see this message.
    when user has seen the message, he will be removed from that list.
    """
    chat = models.ForeignKey(
        'chat.Chat',
        on_delete=models.CASCADE,
        verbose_name=_('chat'),
        )
    creator = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_('creator'),
        )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('created'),
        )
    text = models.TextField(
        verbose_name=_('text'),
        )

    unseen_by = models.ManyToManyField(
        AUTH_USER_MODEL,
        related_name='unseen_messages',
        verbose_name=_('unseen_by'),
        )

    @property
    def previous(self):
        """ get previous chat message
        :returns: ChatMessage or None
        """
        # erstelle liste mit allen objekten
        # index von self
        message_list = sorted(
            list(self.chat.chatmessage_set.all()),
            key=lambda x: x.pk,
            )
        index = message_list.index(self)
        if index and index != len(message_list):
            return message_list[index-1]
        return None

    @property
    def next(self):
        """ get previous chat message
        :returns: ChatMessage or None
        """
        message_list = sorted(
            list(self.chat.chatmessage_set.all()),
            key=lambda x: x.pk,
            reverse=True,
            )
        index = message_list.index(self)
        if index:
            return message_list[index-1]
        return None

    def set_seen_by(self, user):
        """ set message seen by
        :param user: user object that accessed this message
        """
        self.unseen_by.remove(user)
        self.save()

    def save(self, *args, **kwargs):  # pylint: disable=signature-differs
        super().save(*args, **kwargs)
        create_action(self.creator, 'FIRST_CHAT_MESSAGE')

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-pk']
        verbose_name = _('message')
        verbose_name_plural = _('message')


@receiver(post_save, sender=ChatMessage)
# pylint: disable=unused-argument
def create_user_unseen(sender, instance, created, **kwargs):
    """ add all users that should see the chat into unseen_by """
    if created:
        for user in instance.chat.get_users():
            instance.unseen_by.add(user)
        instance.save()


class Chat(models.Model):
    """
    Chats are used by multiple models in different ways:
    User-Chat: Is created by the combination of users (Chat.by_users)
    Market-Chat: Is created within Market.save
    lobby-chat: Is a single object fetched and created by Chat.get_lobby
    """
    users = models.ManyToManyField(
        AUTH_USER_MODEL,
        verbose_name=_('text'),
        )
    type = models.PositiveSmallIntegerField(
        default=ChatType.DEFAULT,
        choices=ChatType.choices,
        verbose_name=_('type'),
        )
    market = models.OneToOneField(
        'market.Market',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name=_('market'),
        )

    @property
    def type_str(self):
        """ get type as string instead of integer
        :returns: str
        """
        return ChatType.by_number(self.type).label

    @property
    def messages(self):
        """ get messages of this chat
        :returns: QuerySet of ChatMessage objects
        """
        return self.chatmessage_set.all()

    def add_message(self, creator, text):
        """ create a chat message from this chat
        :param creator: user object
        :param text: string
        :returns: ChatMessage
        """
        return ChatMessage.objects.create(chat=self, creator=creator, text=text)

    def all_messages_seen_by(self, user):
        """ mark all messages as seen by user
        :param user: User object that has seen all chat messages
        """
        for message in self.messages:
            if user in message.unseen_by.all():
                message.set_seen_by(user)

    def get_users(self):
        """ get users of this chat
        :returns: QuerySet of Users
        """
        if self.type == ChatType.MARKET:
            return self.market.users.all()
        return self.users.all()

    @classmethod
    def get_lobby(cls):
        """ get singleton lobby chat
        :returns: Chat object
        """
        try:
            return cls.objects.get(type=ChatType.LOBBY)
        except Chat.DoesNotExist:
            return cls.objects.create(type=ChatType.LOBBY)

    @classmethod
    def _create_user_object(cls, *users):
        chat = cls.objects.create(type=ChatType.USER)
        for user in users:
            chat.users.add(user)
        chat.save()
        return chat

    @classmethod
    def by_users(cls, *users, create=False):
        """ get chat by user constellation
        :returns: Chat or None
        """
        chats = cls.objects.filter(type=ChatType.USER)
        for chat in chats:
            if set(chat.users.all()) == set(users):
                return chat

        if create:
            chat = cls._create_user_object(*users)
            return chat
        return None

    def save(self, *args, **kwargs):  # pylint: disable=signature-differs
        log_string = 'Chat {}: type={} market={}'.format(
            'updated' if self.pk else 'created',
            str(self.type),
            str(self.market),
            )
        LOGGER.info(log_string)
        super().save(*args, **kwargs)

    def __str__(self):
        if self.type == ChatType.LOBBY:
            return 'Lobby'
        user_str = ', '.join((str(user) for user in self.get_users()))
        return 'Chat [{}]: {}'.format(self.type_str, user_str)

    class Meta:
        ordering = ['-type']
        verbose_name = _('chat')
        verbose_name_plural = _('chats')

core/views.py
""" views of the core module """
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from chat.models import Chat
from action.models import create_action, TASKS
from action.exp import Level


class AboutView(TemplateView):
    """ /about/ """
    template_name = 'sites/about.html'

    def get_context_data(self, **kwargs):
        context = TemplateView.get_context_data(self, **kwargs)
        context['tasks'] = sorted(TASKS)
        context['levels'] = Level.levels()
        return context


class DonateView(TemplateView):
    """ /donate/ """
    template_name = 'sites/donate.html'


class TermsView(TemplateView):
    """ /terms-and-conditions/ """
    template_name = 'sites/terms.html'


class ImpressumView(TemplateView):
    """ /impressum/ """
    template_name = 'sites/impressum.html'


class DashboardHomeView(LoginRequiredMixin, TemplateView):
    """ / """
    template_name = 'dashboard/dashboard_home.html'

    def get_context_data(self, **kwargs):
        if self.request.user.is_authenticated:
            create_action(self.request.user, 'DAILY_VISIT')
        context = TemplateView.get_context_data(self, **kwargs)
        user = self.request.user
        if user.is_authenticated:
            deals = []
            for deal in user.deals:
                deals.append(deal.set_pov(self.request.user))
            context['deals'] = deals
            context['user_feedback_open'] = user.userfeedback_set.filter(
                status=0
                )
            context['push_feedback_open'] = user.pushfeedback_set.filter(
                status=0
                )
            context['lobby'] = Chat.get_lobby()
            # context['chat'] = Chat.get_lobby()
        else:
            self.template_name = 'dashboard/dashboard_anonymous.html'
        return context

core/templates/base.html
{% load static %}{% load pwa %}{% load analytical %}{% load i18n %}
<!DOCTYPE HTML>
<html lang="de-DE">
<head>
  {% analytical_head_top %}
  {% progressive_web_app_meta %}
  <meta charset="UTF-8">
  <title>{{ name }} {% block title %}({{ version_str }}) - Äpfel mit Birnen vergleichen.{% endblock %}</title>
  <meta name="keywords" content="{% block keywords %}{% trans 'push' %}, {% trans 'pull' %}, {% trans 'market' %}, {% trans 'location' %}, {% trans 'deal' %}, {% trans 'feedback' %}, {% trans 'chat' %}, {% trans 'calculator' %}{% endblock %}" />
  <meta name="description" content="{% block description %}Die währungsfreie Tauschbörse für Waren und Dienstleistungen. Angebote und Nachfragen erstellen, Mögliche Tauschvorgänge finden, Tauschvereinbarung aushandeln, Orte erstellen für Umkreissuche, Märkte für regelmäßige Treffen, Bewertungen erstellen, Integrierte Kommunikation (Chat), Tauschwert-Empfehlung{% endblock %}"> 
  <link rel="shortcut icon" type="image/png" href="{% static 'logo.png' %}"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" rel="stylesheet" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% include 'inc/pwa.html' %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <script src="{% static 'js/base.js' %}?v=1"></script>
  <script src="{% static 'js/search.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/base.css' %}?v=2" />
  <style type="text/css">
  </style>
  <script>
  </script>
  {% block head %}{% endblock %}
  {% analytical_head_bottom %}
</head>
<body style="background-color:#15202b;">
  {% analytical_body_top %}
  {% include "menu.html" %}
  <div id="wrapper" class="container bg-white border shadow" style="margin-top:50px;">
    {% if not request.user.is_authenticated %}
      <div class="row mt-4">
        <div class="col-auto align-items-end">
          <a class="btn btn-info mt-2" href="{% url 'user_create' %}"><i class="fas fa-user-plus"></i> {% trans 'free'|title %} {% trans 'signup' %}</a>
        </div>
      </div>
    {% endif %}
    <div class="row">
      <div class="col-12 mt-3">
        <div id="help_block" style="display:none; min-height:54px;" class="alert alert-primary alert-dismissible fade show pt-4" role="alert">
           <div class="container">
            <div class="row">
              <div class="col-12 d-flex justify-content-end">
                <span class="help_button btn">
                  {{ symbols.close|safe }}
                </span>
              </div>
              <div class="row">
                <div class="col-12">
                  {% block help %}Für diese Seite ist noch keine Hilfe vorhanden{% endblock %}
                </div>
              </div>
             </div>
           </div>
        </div>
      </div>
      <div class="col-12">
        <div id="search_results">
          <!-- Search -->
        </div>
      </div>
    </div>
  
    {% if messages %}
      {% for message in messages %}
          <div class="my-3 alert-dismissible fade show alert alert-{{ message.tags }}" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
      {% endfor %}
    {% endif %}
    <div class="row">
      <div class="col-12 p-3 p-xl-5 p-xl-5">{% block content %}{% endblock %}</div>
    </div>
  {% if chat %}
    {% include 'chat/solo/chat_detail.html' %}
  {% endif %}
  </div>
  <div id="footer" class="container">
    <div class="row d-flex justify-content-end">
      <div class="col-auto">
        <a class="btn btn-link text-white" href="{% url 'sitemap' %}"><i class="fas fa-sitemap"></i> sitemap</a>
      </div>
      <div class="col-auto">
        <a class="btn btn-link text-white" href="{% url 'terms' %}"><i class="far fa-handshake"></i>&nbsp;{% trans 'terms-and-conditions'|title %}</a>
      </div>
      <div class="col-auto">
        <a class="btn btn-link text-white" href="{% url 'impressum' %}"><i class="fas fa-align-left"></i>&nbsp;{% trans 'impressum'|title %}</a>
      </div>
    </div>
  </div>
  {% analytical_body_bottom %}
</body>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.17.1/build/styles/default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"></script>
<script type="text/javascript">
$(function () {
	  $('[data-toggle="popover"]').popover({
			html: true,
			content: function(){
				return $(this).find('.popover-content').html();
			}
		})
	})
</script>
</html>

core/templates/menu.html
{% load static %}
{% load i18n %}
<nav id="main_menu" class="navbar navbar-expand shadow d-flex flex-wrap position-fixed w-100 p-0" style="min-height:50px;z-index:10;top:0;background-color:rgb(29, 161, 242);">
  {% if request.user.pk %}
    <ul class="col-auto navbar-nav mr-auto d-flex flex-wrap pr-0" style="height:50px;">
    <li class="nav-item">
      <a class="nav-link p-2" href="{% url 'dashboard_home' %}">
        <!-- <img src="{% static 'images/logo.svg' %}" class="d-inline-block align-top" style="height:40px;" alt=""> -->
        <span class="nav-link pl-1 pt-1">
          <!-- <img src="{% static 'images/nomoney.shop.svg' %}" class="d-inline-block align-top" style="height:35px;" alt=""> -->
          <span class="mr-1">
            <img src="{% static 'images/logo.svg' %}" class="" style="width:25px;" alt=""></span>
            <b class="d-none d-md-inline-block"><span style="text-decoration: underline;">nomone</span><span>y</span><span class="position-relative" style="top:4px;">.shop</span></b>
        </span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link p-3" href="{% url 'category_list' %}">{{ symbols.category|safe }}<span class="d-none d-sm-inline-block pl-1">{% trans 'categories' %}</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link p-3" href="{% url 'calculator' %}">{{ symbols.calculator|safe }}<span class="d-none d-sm-inline-block pl-1">{% trans 'calculator' %}</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link p-3" href="{% url 'chat_list' %}">
          {% if request.user.unseen_messages.all %}
            <span class="badge badge-secondary position-absolute" style="margin-top: 15px;margin-left: -10px;">
              {{ request.user.unseen_messages.all|length }}
            </span>
          {% endif %}
          {{ symbols.chat|safe }}
          <span class="d-none d-sm-inline-block pl-1">{% trans 'chats' %}</span>
        </a>
      </li>
    </ul>
    <ul class="col-auto navbar-nav ml-auto navbar-right pr-0 my-auto" style="height:50px;">
      <li class="nav-item d-flex" title="{% trans 'help' %}">
        <button class="nav-link btn btn-link help_button"><i class="fas fa-info-circle"></i></button>
      </li>
      <li class="nav-item d-flex">
        <div id="search_box" class="collapse d-lg-flex panel-collapse width">
          <input name="text" id="live_search" class="nav-link form-control my-auto" type="search" placeholder="Suche ..." aria-label="Search" autocomplete="off" style="border-radius:0;">
        </div>
      </li>
      <li class="nav-item d-flex d-lg-none">
        <a href="#search_box" class="nav-link align-self-center" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="search_box">
          <span class="">
            {{ symbols.search|safe }}
          </span>
        </a>
      </li>
      <li class="nav-item d-flex">
        <a class="nav-link{% if request.user.image %} p-0{% else %} d-flex justify-content-center{% endif %}" style="width:50px;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {% if request.user.image %}
            <img src="{{ request.user.image.url }}" class="" style="width:50px;" alt=""></img>
            <span class="position-absolute" style="right:16px;bottom:-20px;font-size:large;"><i class="far fa-caret-square-down text-success" style="text-shadow: 0px 0px 10px #fff;"></i></span>
          {% else %}
            <span class="" style="font-size:25px;"><i class="far fa-caret-square-down text-light"></i></span>
          {% endif %}
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'user_detail' request.user.pk %}">{{ symbols.user|safe }} {% trans 'profile' %}</a>
          <a class="dropdown-item" href="{% url 'user_list' %}">{{ symbols.users|safe }} {% trans 'userslist' %}</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">nomoney.shop</h6>
          <a class="dropdown-item" href="{% url 'donate' %}"><i class="fas fa-hand-holding-heart"></i>&nbsp;{% trans 'donate'|title %}</a>
          <a class="dropdown-item" href="{% url 'about' %}"><img src="{% static 'images/logo.svg' %}" class="" style="width:16px;" alt="">&nbsp;{% trans 'about' %}</a>
        </div>
      </li>
    </ul>

  {% else %}
    <div class="container-fluid">
      <div class="row w-100">
        <div class="col-auto my-auto">
          <div class="row m-0">
            <form id="user_form" class="form-inline pl-1" action="{% url 'user_login' %}?next={{ request.path }}" method="post" enctype="multipart/form-data">{% csrf_token %}
              <div class="col p-0">
                {{ form.username }}
              </div>
              <div class="col-auto d-none d-sm-block"></div>
              <div class="col p-0">
                {{ form.password }}
              </div>
              <div class="col-auto btn-group btn-group-sm p-0">
                <button class="btn btn-secondary" type="submit" data-toggle="tooltip" title="login"><i class="fas fa-sign-in-alt"></i></button>
              </div>
            </form>
          </div>
        </div>
      
        <div class="col d-flex justify-content-center">
            <div class="col d-flex pr-0 d-flex justify-content-center">
              <i class="align-self-center fas fa-arrow-right text-light"></i>
            </div>
            <div class="col d-flex pr-0 d-flex justify-content-center">
              <b class="align-self-center m-0 text-nowrap text-light">{% trans 'or' %} {% trans 'login' %} {% trans 'with' %}</b>
            </div>
            <div class="col d-flex pr-0 d-flex justify-content-center">
              <i class="align-self-center fas fa-arrow-right text-light"></i>
            </div>
        </div>
        
        <div class="col d-flex justify-content-end">
          <div class="row">
            <div class="col-auto d-flex justify-content-end">
              <a class="btn btn-link p-0 m-0 d-flex text-shadow" href="{% url 'social:begin' 'github' %}">
                <i class="fab fa-github-square fa-2x" style="color:#171515;"></i>
                <span class="align-self-center pl-2 text-light"><b>Github</b></span>
              </a>
            </div>
            <div class="col-auto d-flex justify-content-end">
              <a class="btn btn-link p-0 m-0 d-flex text-shadow" href="{% url 'social:begin' 'twitter' %}">
                <i class="fab fa-twitter-square fa-2x" style="color:#1dabdd;"></i>
                <span class="align-self-center pl-2 text-light"><b>Twitter</b></span>
              </a>
            </div>
            <div class="col-auto d-flex justify-content-end">
              <a class="btn btn-link p-0 m-0 d-flex text-shadow" href="{% url 'social:begin' 'facebook' %}">
                <i class="fab fa-facebook-square fa-2x" style="color:#3b579d;"></i>
                <span class="align-self-center pl-2 text-light"><b>Facebook</b></span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
</nav>

core/templates/offline.html
{% extends 'base.html' %}
{% load i18n %}

{% block help %}
{% endblock %}
{% block content %}
    <div class="container">
      <div class="row">
        <div class="col-12 w-100 d-flex justify-content-center">
            <p>{% trans 'you' %} {% trans 'are' %} {% trans 'offline' %} ...</p>
        </div>
        <div class="col-12 w-100 d-flex justify-content-center" style="height: 100px;">
          <div class="spinner-border my-auto" role="status">
            <span class="sr-only">{% trans 'load'|title %} {% trans 'data' %}...</span>
          </div>
        </div>
      </div>
    </div>
{% endblock %}