bid/urls.py
""" urls for the bid module """
from django.urls import path
from .views import BidListView, BidCreateView, BidDetailView, BidDeleteView


urlpatterns = [
    path('', BidListView.as_view(), name='bid_list'),
    # path('partner/<int:partner_pk>/', BidListView.as_view(), name='bid_list'),
    #path('partner/<int:partner_pk>/new/', BidCreateView.as_view(), name='bid_create'),
    path('for/deal/<int:deal_pk>/new/', BidCreateView.as_view(), name='bid_create'),
    path('<int:pk>/', BidDetailView.as_view(), name='bid_detail'),
    path('<int:pk>/update/', BidDetailView.as_view(), name='bid_update'),
    path('<int:bid_pk>/delete/', BidDeleteView.as_view(), name='bid_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from config import settings


urlpatterns = [
    path('', include('core.urls')),
    path('bid/', include('bid.urls')),
    path('user/', include('user.urls')),
    path('category/', include('category.urls')),
    path('listing/', include('listing.urls')),
    path('search/', include('search.urls')),
    path('chat/', include('chat.urls')),
    path('deal/', include('deal.urls')),
    path('market/', include('market.urls')),
    path('feedback/', include('feedback.urls')),
    path('location/', include('location.urls')),
    path('calculator/', include('calculator.urls')),

    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('pwa.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/urls.py
""" urls for feedback module (/feedback/*) """
from django.urls import path
from .views import FeedbackUpdateView, FeedbackDeleteView, FeedbackListView, \
    FeedbackTypeListView


urlpatterns = [
    path('', FeedbackListView.as_view(), name='feedback_list'),
    path('<slug:type>/<int:pk>/', FeedbackTypeListView.as_view(), name='feedback_detail'),
    path('<slug:type>/<int:pk>/update/', FeedbackUpdateView.as_view(), name='feedback_update'),
    path('<slug:type>/<int:pk>/delete/', FeedbackDeleteView.as_view(), name='feedback_delete'),
]

feedback/models.py
""" models for feedback module """
from django.utils.translation import gettext_lazy as _
from django.db import models
from config.settings import AUTH_USER_MODEL, LOGGER
from action.models import create_action


class FeedbackStatus(models.IntegerChoices):
    """ Status of a feedback
    REQUEST - Feedback created by system when finishing a deal
    SENT - Requested feedback was created by user
    CANCELED - Requested feedback was canceled by user
    """
    REQUEST = 0, _('request')
    SENT = 100, _('sent')
    CANCELED = 110, _('canceled')


class FeedbackBase(models.Model):
    """ base class for all kind of feedback """
    creator = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_('creator'),
        )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('created'),
        )
    score = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        verbose_name=_('score'),
        )  # 0-100
    subject = models.CharField(
        max_length=30,
        null=True,
        blank=True,
        verbose_name=_('subject'),
        )
    text = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('text'),
        )
    status = models.PositiveSmallIntegerField(
        default=FeedbackStatus.REQUEST,
        choices=FeedbackStatus.choices,
        verbose_name=_('status'),
        )
    deal = models.ForeignKey(
        'deal.Deal',
        on_delete=models.CASCADE,
        verbose_name=_('deal'),
        )
    type, push, user = 3 * [None]

    @property
    def object(self):
        """ returns the object the feedback was created for
        :returns: User or Push object
        """
        return self.user or self.push

    @property
    def is_editable(self):
        """ calculates if the feedback is editable
        :returns: bool
        """
        return self.status == FeedbackStatus.REQUEST

    def set_sent(self):
        """ set the status to FeedbackStatus.SENT """
        self.status = FeedbackStatus.SENT
        self.save()

    def save(self, *args, **kwargs):  # pylint: disable=signature-differs
        log_string = 'Feedback {}: type={} creator={} object={} score={} status={}'.format(
            'updated' if self.pk else 'created',
            str(self.type),
            str(self.creator),
            str(self.object),
            str(self.score),
            str(self.status),
            )
        LOGGER.info(log_string)
        super().save(*args, **kwargs)

    def __str__(self):
        return '{}: {}'.format(self.type, self.object)

    class Meta:
        abstract = True


class UserFeedback(FeedbackBase):
    """ Feedback for a user """
    type = 'user'
    user = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='feedback_for',
        verbose_name=_('user'),
        )

    @classmethod
    def given_by_user(cls, user):
        """ userfeedbacks given by user
        :param user: User to fetch feedbacks of
        :returns: QuerySet(UserFeedback)
        """
        return cls.objects.filter(creator__pk=user.pk)

    @classmethod
    def taken_by_user(cls, user):
        """ userfeedbacks taken by user
        :param user: User to fetch feedbacks of
        :returns: QuerySet(UserFeedback)
        """
        return cls.objects.filter(user__pk=user.pk)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        create_action(self.creator, 'USER_FEEDBACK_GIVEN')
        create_action(self.user, 'USER_FEEDBACK_TAKEN')

    class Meta:
        verbose_name = _('userfeedback')
        verbose_name_plural = _('userfeedbacks')


class PushFeedback(FeedbackBase):
    """ Feedback for a push """
    type = 'push'
    push = models.ForeignKey('listing.Push', on_delete=models.CASCADE)

    @classmethod
    def given_by_user(cls, user):
        """ pushfeedbacks given by user
        :param user: User to fetch feedbacks of
        :returns: QuerySet(PushFeedback)
        """
        return cls.objects.filter(creator__pk=user.pk)

    @classmethod
    def taken_by_user(cls, user):
        """ pushfeedbacks taken by user
        :param user: User to fetch feedbacks of
        :returns: QuerySet(PushFeedback)
        """
        return cls.objects.filter(push__user__pk=user.pk)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        create_action(self.creator, 'PUSH_FEEDBACK_GIVEN')
        create_action(self.push.user, 'PUSH_FEEDBACK_TAKEN')

    class Meta:
        verbose_name = _('pushfeedback')
        verbose_name_plural = _('pushfeedbacks')

feedback/forms.py
""" forms for the feedback module """
from django import forms
from .models import PushFeedback, UserFeedback


class PushFeedbackUpdateForm(forms.ModelForm):
    """ form for updating push feedbacks """

    class Meta:
        fields = ['score', 'subject', 'text']
        model = PushFeedback


class UserFeedbackUpdateForm(forms.ModelForm):
    """ form for updating push feedbacks """

    class Meta:
        fields = ['score', 'subject', 'text']
        model = UserFeedback

feedback/views.py
""" views for the feedback module """
from operator import attrgetter
from django.views.generic.base import TemplateView, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView
from django import forms
from django.urls.base import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from listing.models import Push
from .models import UserFeedback, PushFeedback


class FeedbackContextMixin(TemplateView):
    """ dry """
    @staticmethod
    def get_feedback_by_user(user):
        """ fetch the feedback lists
        :returns: list[[UserFeedback.taken],[PushFeedback.taken],
                                    [UserFeedback.given],[PushFeedback.given]]
        """
        methods = (
            UserFeedback.taken_by_user,
            PushFeedback.taken_by_user,
            UserFeedback.given_by_user,
            PushFeedback.given_by_user
            )
        return [list(method_(user).exclude(status=0)) for method_ in methods]

    @classmethod
    def get_feedback(cls, user):
        """ sorts the objects from get_feedback_by_user and gives them back
        :returns: [feedback_given], [feedback_taken]
        """
        user_taken, push_taken, user_given, push_given = cls.get_feedback_by_user(user)
        return sorted((user_taken + push_taken), key=attrgetter('created'), reverse=True), \
            sorted((user_given + push_given), key=attrgetter('created'), reverse=True)

    def get_context_data(self, **kwargs):
        context = TemplateView.get_context_data(self, **kwargs)
        user = self.request.user
        if self.type == 'push':
            push = Push.objects.get(pk=self.pk_)
            context['push_feedback_taken'] = push.pushfeedback_set.exclude(status=0)
            context['push'] = push
        else:
            context['user_feedback_given'], context['user_feedback_taken'] = \
                self.get_feedback(user)
        context['user'] = user
        return context


class FeedbackTypeListView(FeedbackContextMixin, LoginRequiredMixin, TemplateView):
    """ List feedback objects of type for direct access """
    template_name = 'feedback/feedback_list.html'
    user = None
    type, pk_ = 2 * [None]

    def setup(self, request, *args, **kwargs):
        self.type = kwargs.get('type')
        self.pk_ = kwargs.get('pk')
        ListView.setup(self, request, *args, **kwargs)


class FeedbackListView(FeedbackContextMixin, LoginRequiredMixin, TemplateView):
    """ List feedback """
    template_name = 'feedback/feedback_list.html'


class FeedbackUpdateView(LoginRequiredMixin, UpdateView):
    """ UpdateView to update a feedback """
    model = None
    template_name = 'feedback/feedback_form.html'
    fields = ['score', 'subject', 'text']
    type_, deal = 2 * [None]

    def setup(self, request, *args, **kwargs):
        self.type_ = kwargs.get('type')
        self.model = {
            'user': UserFeedback,
            'push': PushFeedback,
            }.get(self.type_)
        self.deal = self.model.objects.get(pk=kwargs.get('pk')).deal
        UpdateView.setup(self, request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = UpdateView.get_context_data(self, **kwargs)
        context['deal'] = self.deal
        return context

    def get_form(self, form_class=None):
        form = UpdateView.get_form(self, form_class=form_class)
        form.fields['score'].widget = forms.HiddenInput()
        return form

    def form_valid(self, form):
        response = UpdateView.form_valid(self, form)
        self.get_object().set_sent()
        return response

    def get_success_url(self):
        return reverse('feedback_list')


class FeedbackDetailDeleteBase(LoginRequiredMixin, View):
    """ Baseview for Feedback Detail and Delete View """
    model = None
    type_ = None
    template_name = 'feedback/feedback_detail.html'

    def setup(self, request, *args, **kwargs):
        self.type_ = kwargs.get('type')
        self.model = {'user': UserFeedback, 'push': PushFeedback}.get(self.type_)
        DetailView.setup(self, request, *args, **kwargs)


class FeedbackDetailView(FeedbackDetailDeleteBase, DetailView):
    """ DetailView of a single feedback """


class FeedbackDeleteView(FeedbackDetailDeleteBase, DeleteView):
    """ DeleteView to delete a feedback """

feedback/templates/feedback/feedback_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

<!-- if object.type == 'push' 
list object.feedbacks
-->

<!-- list user.feedbacks -->
<!-- list user.received_feedbacks -->
<!-- list user.pushs.feedbacks -->

{% endblock %}

feedback/templates/feedback/feedback_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block head %}
<script>
$( document ).ready(function() {
  var score = $('#id_score').val();
  if (score == ''){
	  score = 50;
  }
  $(this).find('.progress-bar').html(score + '%');
  $(this).find('.progress-bar').css('width', score + '%');

  $("#progress").click(function(e){
      var x = e.pageX - $(this).offset().left;
      var x_pct = x / $(this).width() *100;
      $('#id_score').val(x_pct.toFixed(0));
  });

  $("#progress").mousemove(function(e){
      var x = e.pageX - $(this).offset().left;
      var x_pct = x / $(this).width() *100;
      if (x_pct >= 95){
    	  x_pct = 100;
      } else if (x_pct <=5){
    	  x_pct = 0;
      }
      $(this).find('.progress-bar').html(x_pct.toFixed(0)+ '%');
      $(this).find('.progress-bar').css('width', x_pct+ '%');
  });

  $("#progress").mouseleave(function(){
	  var score = $('#id_score').val();
	  if (score == ''){
		  score = 50;
	  }
      $(this).find('.progress-bar').html(score + '%');
      $(this).find('.progress-bar').css('width', score + '%');
  });
}); 
</script>
{% endblock %}


{% block content %}
{% include 'deal/solo/deal_detail.html' %}

<div class="container mt-5">
  <div class="row">
    <div class="col-12"><h3>{% trans 'feedback'|title %} {% trans 'create' %}:</h3></div>
  </div>
  <form method="post">
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {{ form.errors }}
      </div>
    {% else %}
    {% endif %}
    {% csrf_token %}
    <table class="table table-striped table-bordered table-hover">
    <tr>
    <th>Score:</th>
    <td>
      <div id="progress" class="progress bg-white">
        <div class="progress-bar" role="progressbar" style="width: 50%;">50%</div>
      </div>
    </td>
    </tr>
      {{ form.as_table }}
    </table>
    <button class="btn btn-primary btn-block" type="submit">{% trans 'save'|title %}</button>
  </form>
</div>
{% endblock %}

feedback/templates/feedback/feedback_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<!-- if request.user == object.user 
offene bewertungen anzeigen
-->
{% if user and user_feedback_taken %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h5>
          {{ symbols.feedback_regular|safe }} {% trans 'feedbacks'|title %} <b>{% trans 'for' %}</b> {{ user }}
        </h5>
      </div>
    </div>
    {% with feedbacks=user_feedback_taken %}
      {% include 'feedback/solo/list.html' %}
    {% endwith %}
  </div>
  <hr class="my-5">
{% endif %}

{% if user and user_feedback_given %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h5>
          {{ symbols.feedback_regular|safe }} {% trans 'feedbacks'|title %} <b>{% trans 'from' %}</b> {{ user }}
        </h5>
      </div>
    </div>
    {% with feedbacks=user_feedback_given %}
      {% include 'feedback/solo/list.html' %}
    {% endwith %}
  </div>
  <hr class="my-5">
{% endif %}


{% if push and push_feedback_taken %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h5>
          {{ symbols.feedback_regular|safe }} {% trans 'feedbacks'|title %} <b>{% trans 'for' %}</b> {{ push }}
        </h5>
      </div>
    </div>
    {% with feedbacks=push_feedback_taken %}
      {% include 'feedback/solo/list.html' %}
    {% endwith %}
  </div>
  <hr class="my-5">
{% endif %}

{% if push and push_feedback_given %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h5>
          {{ symbols.feedback_regular|safe }} {% trans 'feedbacks'|title %} <b>{% trans 'from' %}</b> {{ push }}
        </h5>
      </div>
    </div>
    {% with feedbacks=push_feedback_given %}
      {% include 'feedback/solo/list.html' %}
    {% endwith %}
  </div>
  <hr class="my-5">
{% endif %}



<!-- Benutzer bewertungen erhalten -->

<!-- Benutzer bewertungen gegeben -->

<!-- Push bewertungen erhalten -->

<!-- Push bewertungen gegeben -->

{% endblock %}

feedback/templates/feedback/feedback_user.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
  {% include 'feedback/solo/list.html' %}
{% endblock %}